### ISSUE TITLE
will it be a plugin version for elasticsearch 1.7.x ?

### ISSUE THREAD

**Issue by ld57** [codelibs/elasticsearch-auth#19]
hello,

I wonder if you still maintain your plugin for new release of ES .

Best regards,

ld

**Comment by sateng** [comment]
on the plugin description it says:

Auth	        Tested On Elasticsearch
master	1.7.x

so it should be working on elasticsearch 1.7.x

**Comment by ld57** [comment]
Yep I tested it and it works.
